### PR TITLE
[WIP] Release v0.14.0

### PR DESCRIPTION
**Pull request by Glutexo**
There is a new method `Project#last_update` introduced by #102. This is needed by manageiq/manageiq-providers-ansible_tower#73.

Are there any other changes, fixes, features that are going to be included in `v0.14`?

This PR is currently based on the aforementioned #102:

* [x] Depends on #102 to be merged first.

@jrafanie @bdunne @jameswnl

### CODE REVIEW

**Comment by jrafanie** [comment]
@Glutexo Please put [WIP] in the PR title and add 

- [ ] depends on https://github.com/ansible/ansible_tower_client_ruby/pull/102 to be merged first

**Comment by jrafanie** [comment]
@miq-bot add_label wip

**Comment by bdunne** [comment]
@Glutexo I released v0.14.0, so this can be closed.

**Comment by Glutexo** [comment]
Released by @bdunne. Closing.

**Pull request closed without merging**
