### PR TITLE
Accessing nodes for workflow jobs

### PR DESCRIPTION
**Pull request by jameswnl**

### CODE REVIEW

**Comment by jameswnl** [comment]
@miq-bot add_labels enhancment

**Comment by jameswnl** [comment]
@bzwei @lfu @tinaafitz See if this works for you

**Comment by jameswnl** [comment]
@miq-bot add_labels wip, enhancement

**Comment by gmcculloug** [comment]
@jameswnl Any ETA on getting tests passing here?

**Comment by jameswnl** [comment]
@gmcculloug this is just weird, it is passing on my local and my travis https://travis-ci.org/jameswnl/ansible_tower_client_ruby/jobs/394753888
Any suggestion will be welcome

**Comment by jameswnl** [comment]
@miq-bot remove_label wip

**Comment by lfu** [comment]
@bdunne Please release a new gem. https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/103 depends on this.

**Pull request merged**
